-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim
-- Default Neovim Colorscheme with some tweaks

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = 'bamoon'

-- Highlight groups
local hi = vim.api.nvim_set_hl

local colors = {
  purple = '#b294bb',
  yellow = '#fbfead',
  blue = '#7aa0bb',
  green = '#b3f6c0',
  red = '#cc6666',
  gold = '#d4aa55',
  grey = '#b0b1b0',
  cyan = '#89dceb',
  white = '#e0e0e0',
  black = '#292a30',

  dark_purple = '#8e6fbd',
  dark_red = '#bf4040',
  dark_yellow = '#f8fe7a',
  dark_blue = '#5f89ad',
  dark_grey = '#4e545d',
  dark_gold = '#8f7436',
  dark_black = '#14161B',
  dark_black2 = '#04070d',

  mate_green0 = '#597b60',
  mate_green1 = '#005523',
  mate_blue0 = '#467c7b',
  mate_red0 = '#7f605c',
  mate_grey0 = '#77787c',
  mate_grey1 = '#4f5258',
  mate_grey2 = '#45475a',
}

hi(0, 'WinBorder', { link = 'Statusline' })
hi(0, "Normal", { bg = colors.dark_black, fg = colors.white })
-- hi(0, "NormalFloat", { bg = colors.dark_black2, fg = colors.white })
hi(0, "TermCursor", { fg = colors.white, bg = colors.dark_black2 })
hi(0, "NormalNC", { link = "Normal" })
hi(0, "NormalSB", { link = "NormalFloat" })
hi(0, "FloatBorder", { fg = colors.white })
hi(0, 'Keyword', { fg = colors.purple })
hi(0, 'Typedef', { fg = colors.dark_yellow })
hi(0, 'Function', { fg = colors.blue })
hi(0, 'Character', { fg = colors.red })
hi(0, 'Statement', { fg = colors.dark_red })
hi(0, 'Whitespace', { fg = colors.dark_purple })
hi(0, 'Identifier', { link = 'NvimDarkGrey3' })
hi(0, 'Type', { fg = colors.yellow })
hi(0, 'Number', { fg = colors.gold })
hi(0, 'Constant', { fg = colors.gold })
hi(0, 'Comment', { fg = colors.grey, italic = true })
hi(0, 'Conceal', { bg = colors.dark_grey, fg = colors.dark_black, italic = true })
hi(0, 'Conditional', { fg = colors.purple, italic = true })
hi(0, 'Operator', { fg = colors.cyan })
hi(0, 'Directory', { fg = colors.blue })
hi(0, 'Tag', { bold = true, fg = colors.white })
hi(0, 'Error', { fg = colors.red })
hi(0, 'ErrorMsg', { link = 'Error' })
hi(0, 'Exception', { fg = colors.purple })
hi(0, 'Include', { fg = colors.red })
hi(0, 'healthError', { fg = colors.red })
hi(0, 'healthSuccess', { fg = colors.white })
hi(0, 'healthWarning', { fg = colors.yellow })
hi(0, 'DiagnosticError', { fg = colors.red, italic = true })
hi(0, 'DiagnosticFloatingError', { fg = colors.red })
hi(0, 'DiagnosticFloatingHint', { fg = colors.white })
hi(0, 'DiagnosticFloatingInfo', { fg = colors.cyan })
hi(0, 'DiagnosticFloatingOk', { fg = colors.green })
hi(0, 'DiagnosticFloatingWarn', { fg = colors.yellow })
hi(0, 'DiagnosticHint', { fg = colors.white, italic = true })
hi(0, 'DiagnosticInfo', { fg = colors.cyan, italic = true })
hi(0, 'DiagnosticOk', { fg = colors.green, italic = true })
hi(0, 'DiagnosticSignError', { fg = colors.red })
hi(0, 'DiagnosticSignHint', { fg = colors.white })
hi(0, 'DiagnosticSignInfo', { fg = colors.cyan })
hi(0, 'DiagnosticSignOk', { fg = colors.green })
hi(0, 'DiagnosticSignWarn', { fg = colors.yellow })
hi(0, 'DiagnosticUnderlineError', { sp = colors.red, underline = true })
hi(0, 'DiagnosticUnderlineHint', { sp = colors.white, underline = true })
hi(0, 'DiagnosticUnderlineInfo', { sp = colors.cyan, underline = true })
hi(0, 'DiagnosticUnderlineWarn', { sp = colors.yellow, underline = true })
hi(0, 'DiagnosticVirtualTextError', { fg = colors.red, italic = true })
hi(0, 'DiagnosticVirtualTextHint', { fg = colors.white, italic = true })
hi(0, 'DiagnosticVirtualTextInfo', { fg = colors.cyan, italic = true })
hi(0, 'DiagnosticVirtualTextOk', { fg = colors.green, italic = true })
hi(0, 'DiagnosticVirtualTextWarn', { fg = colors.yellow, italic = true })
hi(0, 'DiagnosticWarn', { fg = colors.yellow, italic = true })
hi(0, 'PreProc', { fg = colors.cyan })
hi(0, '@character.special', { bold = true, fg = colors.red })
hi(0, '@tag', { fg = colors.purple })
hi(0, '@tag.attribute', { fg = colors.white, italic = true })
hi(0, '@tag.attribute.vue', { link = 'Type' })
hi(0, '@tag.attribute.tsx', { fg = colors.white, italic = true })
hi(0, '@tag.attribute.heex', { fg = colors.white, italic = true })
hi(0, '@tag.delimiter', { fg = colors.cyan })
hi(0, '@attribute', { link = 'Constant' })
hi(0, '@error', { link = 'Error' })
hi(0, '@float', { link = 'float' })
hi(0, '@exception', { link = 'Exception' })
hi(0, '@symbol', { fg = colors.dark_gold })
hi(0, '@module', { fg = colors.white, italic = true })
hi(0, '@namespace', { fg = colors.white, italic = true })
hi(0, '@keyword.conditional', { link = 'Conditional' })
hi(0, '@keyword.conditional.ternary', { link = 'Operator' })
hi(0, '@keyword.coroutine', { link = 'Keyword' })
hi(0, '@keyword.debug', { link = 'Exception' })
hi(0, '@keyword.directive', { link = 'PreProc' })
hi(0, '@keyword.directive.define', { link = 'Define' })
hi(0, '@keyword.exception', { link = 'Exception' })
hi(0, '@keyword.export', { fg = colors.cyan })
hi(0, '@keyword.function', { fg = colors.purple })
hi(0, '@keyword.import', { link = 'Include' })
hi(0, '@keyword.modifier', { link = 'Keyword' })
hi(0, '@keyword.operator', { link = 'Operator' })
hi(0, '@keyword.repeat', { link = 'Repeat' })
hi(0, '@keyword.return', { fg = colors.purple })
hi(0, '@keyword.storage', { link = 'Keyword' })
hi(0, '@keyword.type', { link = 'Keyword' })
hi(0, '@attribute.builtin', { link = 'Special' })
hi(0, '@comment.error', { link = 'DiagnosticError' })
hi(0, '@comment.note', { link = 'DiagnosticInfo' })
hi(0, '@comment.todo', { link = 'Todo' })
hi(0, '@comment.warning', { link = 'DiagnosticWarn' })
hi(0, '@constant.builtin', { link = 'Special' })
hi(0, '@function.builtin', { link = '@variable.builtin' })
hi(0, '@function.call.lua', { fg = colors.dark_blue })
hi(0, '@lsp.mod.deprecated', { link = 'DiagnosticDeprecated' })
hi(0, '@lsp.type.class', { link = '@type' })
hi(0, '@lsp.type.decorator', { link = '@attribute' })
hi(0, '@lsp.type.event', { link = '@type' })
hi(0, '@lsp.type.function', { link = '@function' })
hi(0, '@lsp.type.interface', { link = '@type' })
hi(0, '@lsp.type.macro', { link = '@constant.macro' })
hi(0, '@lsp.type.method', { link = '@function.method' })
hi(0, '@lsp.type.modifier', { link = '@type.qualifier' })
hi(0, '@lsp.type.regexp', { link = '@string.regexp' })
hi(0, '@lsp.type.string', { link = '@string' })
hi(0, '@lsp.type.struct', { link = '@type' })
hi(0, '@lsp.type.type', { link = '@type' })
hi(0, '@lsp.type.typeParameter', { link = '@type.definition' })
hi(0, '@lsp.type.variable', { link = '@variable' })
hi(0, '@markup.heading', { link = 'Title' })
hi(0, '@module.builtin', { link = 'Special' })
hi(0, '@string.escape', { link = '@string.special' })
hi(0, '@string.regexp', { link = '@string.special' })
hi(0, '@string.special.url', { link = 'Underlined' })
hi(0, '@string.special.symbol', { link = '@variable.builtin' })
hi(0, '@tag.builtin', { link = 'Special' })
hi(0, '@type.builtin', { link = 'Type' })
hi(0, '@variable', { fg = colors.white })
hi(0, '@variable.builtin', { fg = colors.red })
hi(0, '@variable.member', { fg = colors.white })
hi(0, '@variable.member.vue', { link = 'Identifier' })
hi(0, '@variable.parameter', { fg = colors.white })
hi(0, '@variable.parameter.builtin', { link = 'Special' })
hi(0, '@function.bracket', { fg = colors.white })
hi(0, 'Pmenu', { bg = colors.black, fg = colors.white, bold = true })
hi(0, 'PmenuKind', { link = 'Pmenu' })
hi(0, 'CmpItemKindClassDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindColorDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindConstantDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindConstructorDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindEnumDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindEnumMemberDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindEventDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindFieldDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindFileDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindFolderDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindFunctionDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindInterfaceDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindKeywordDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindMethodDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindModuleDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindOperatorDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindPropertyDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindReferenceDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindSnippetDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindStructDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindTextDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindTypeParameterDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindUnitDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindValueDefault', { link = 'CmpItemKind' })
hi(0, 'CmpItemKindVariableDefault', { link = 'CmpItemKind' })
hi(0, 'GitSignsStagedAdd', { fg = colors.mate_green0 })
hi(0, 'GitSignsStagedAddLn', { bg = colors.mate_green1, fg = colors.mate_grey0 })
hi(0, 'GitSignsStagedAddNr', { fg = colors.mate_green0 })
hi(0, 'GitSignsStagedChange', { fg = colors.mate_blue0 })
hi(0, 'GitSignsStagedChangeLn', { bg = colors.mate_grey1, fg = colors.mate_grey0 })
hi(0, 'GitSignsStagedChangeNr', { fg = colors.mate_blue0 })
hi(0, 'GitSignsStagedChangedelete', { fg = colors.mate_blue0 })
hi(0, 'GitSignsStagedChangedeleteLn', { bg = colors.mate_grey1, fg = colors.mate_grey0 })
hi(0, 'GitSignsStagedChangedeleteNr', { fg = colors.mate_blue0 })
hi(0, 'GitSignsStagedDelete', { fg = colors.mate_red0 })
hi(0, 'GitSignsStagedDeleteNr', { fg = colors.mate_red0 })
hi(0, 'GitSignsStagedTopdelete', { fg = colors.mate_red0 })
hi(0, 'GitSignsStagedTopdeleteNr', { fg = colors.mate_red0 })
hi(0, 'MiniDiffOverAdd', { link = 'GitSignsStagedAdd' })
hi(0, 'MiniDiffOverChange', { link = 'GitSignsStagedChange' })
hi(0, 'MiniDiffOverDelete', { link = 'GitSignsStagedDelete' })
hi(0, 'MiniStatuslineDevinfo', { link = 'StatusLine' })
hi(0, 'MiniStatuslineFileinfo', { link = 'MiniStatuslineDevinfo' })
hi(0, 'MiniStatuslineFilename', { link = 'StatusLineNC' })
hi(0, 'MiniStatuslineInactive', { link = 'MiniStatuslineFilename' })
hi(0, 'MiniStatuslineModeCommand', { link = 'DiffText' })
hi(0, 'MiniStatuslineModeInsert', { link = 'DiffChange' })
hi(0, 'MiniStatuslineModeNormal', { link = 'RedrawDebugNormal' })
hi(0, 'MiniStatuslineModeOther', { link = 'IncSearch' })
hi(0, 'MiniStatuslineModeReplace', { link = 'DiffDelete' })
hi(0, 'MiniStatuslineModeVisual', { link = 'DiffAdd' })
hi(0, 'MiniNotifyNormal', { })
hi(0, 'MiniNotifyBorder', { link = 'FloatBorder' })
hi(0, 'MiniNotifyLspProgress', { link = 'Keyword'})
hi(0, 'MiniNotifyTitle', { link = 'Function'})
hi(0, 'MiniPickPromptPrefix', { fg = colors.dark_red })
hi(0, 'MiniPickPromptCaret', { fg = colors.dark_purple })
hi(0, 'LspReferenceRead', { bg = colors.mate_grey2 })
hi(0, 'LspReferenceText', { bg = colors.mate_grey2 })
hi(0, 'LspReferenceWrite', { bg = colors.mate_grey2 })
hi(0, 'LspSignatureActiveParameter', { fg = colors.gold })
hi(0, 'FzfLuaBackdrop', { link = 'NvimDarkGrey4' })
hi(0, '@label', { fg = colors.dark_yellow })
