-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim
-- Default Neovim Colorscheme with some tweaks

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "bamoon"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "Keyword", { fg = "#b294bb" })
hi(0, "Function", { fg = "#7aa0bb" })
hi(0, "Statement", { fg = "#b294bb" })
hi(0, "Type", { fg = "#fbfead" })
hi(0, "Number", { fg = "#d4aa55" })
hi(0, "Constant", { fg = "#d4aa55" })
hi(0, "Conditional", { fg = "#b294bb", italic = true })
hi(0, "Operator", { fg = "#89dceb" })
hi(0, "Directory", { fg = "#7aa0bb" })
hi(0, "Tag", { bold = true, fg = "#e0e0e0" })
hi(0, "Error", { fg = "#cc6666" })
hi(0, "ErrorMsg", { link = "Error" })
hi(0, "Exception", { fg = "#b294bb" })
hi(0, "Include", { fg = "#cc6666" })
hi(0, "healthError", { fg = "#cc6666" })
hi(0, "healthSuccess", { fg = "#e0e0e0" })
hi(0, "healthWarning", { fg = "#fbfead" })
hi(0, "DiagnosticError", { fg = "#cc6666", italic = true })
hi(0, "DiagnosticFloatingError", { fg = "#cc6666" })
hi(0, "DiagnosticFloatingHint", { fg = "#e0e0e0" })
hi(0, "DiagnosticFloatingInfo", { fg = "#89dceb" })
hi(0, "DiagnosticFloatingOk", { fg = "#b3f6c0" })
hi(0, "DiagnosticFloatingWarn", { fg = "#fbfead" })
hi(0, "DiagnosticHint", { fg = "#e0e0e0", italic = true })
hi(0, "DiagnosticInfo", { fg = "#89dceb", italic = true })
hi(0, "DiagnosticOk", { fg = "#b3f6c0", italic = true })
hi(0, "DiagnosticSignError", { fg = "#cc6666" })
hi(0, "DiagnosticSignHint", { fg = "#e0e0e0" })
hi(0, "DiagnosticSignInfo", { fg = "#89dceb" })
hi(0, "DiagnosticSignOk", { fg = "#b3f6c0" })
hi(0, "DiagnosticSignWarn", { fg = "#fbfead" })
hi(0, "DiagnosticUnderlineError", { sp = "#cc6666", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#e0e0e0", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#89dceb", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#fbfead", underline = true })
hi(0, "DiagnosticVirtualTextError", { fg = "#cc6666", italic = true })
hi(0, "DiagnosticVirtualTextHint", { fg = "#e0e0e0", italic = true })
hi(0, "DiagnosticVirtualTextInfo", { fg = "#89dceb", italic = true })
hi(0, "DiagnosticVirtualTextOk", { fg = "#b3f6c0", italic = true })
hi(0, "DiagnosticVirtualTextWarn", { fg = "#fbfead", italic = true })
hi(0, "DiagnosticWarn", { fg = "#fbfead", italic = true })
hi(0, "PreProc", { fg = "#89dceb" })
hi(0, "@tag", { fg = "#b294bb" })
hi(0, "@tag.attribute", { fg = "#e0e0e0", italic = true })
hi(0, "@tag.attribute.tsx", { fg = "#e0e0e0", italic = true })
hi(0, "@tag.attribute.heex", { fg = "#e0e0e0", italic = true })
hi(0, "@tag.delimiter", { fg = "#89dceb" })
hi(0, "@attribute", { link = "Constant" })
hi(0, "@error", { link = "Error" })
hi(0, "@float", { link = "float" })
hi(0, "@exception", { link = "Exception" })
hi(0, "@symbol", { fg = "#8f7436" })
hi(0, "@module", { fg = "#e0e0e0", italic = true })
hi(0, "@namespace", { fg = "#e0e0e0", italic = true })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.conditional.ternary", { link = "Operator" })
hi(0, "@keyword.coroutine", { link = "Keyword" })
hi(0, "@keyword.debug", { link = "Exception" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.export", { fg = "#89dceb" })
hi(0, "@keyword.function", { fg = "#b294bb" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.modifier", { link = "Keyword" })
hi(0, "@keyword.operator", { link = "Operator" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { fg = "#b294bb" })
hi(0, "@keyword.storage", { link = "Keyword" })
hi(0, "@keyword.type", { link = "Keyword" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@comment.error", { link = "DiagnosticError" })
hi(0, "@comment.note", { link = "DiagnosticInfo" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { link = "DiagnosticWarn" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@function.builtin", { link = "@variable.builtin" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", { link = "@variable" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@string.escape", { link = "@string.special" })
hi(0, "@string.regexp", { link = "@string.special" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@string.special.symbol", { link = "@variable.builtin" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@type.builtin", { link = "Type" })
hi(0, "@variable", { fg = "#cdd6f4" })
hi(0, "@variable.builtin", { fg = "#cc6666" })
hi(0, "@variable.member", { fg = "#e0e0e0" })
hi(0, "@variable.parameter", { fg = "#e0e0e0" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#9b9ea4" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#8cf8f7" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "GitSignsStagedAdd", { fg = "#597b60" })
hi(0, "GitSignsStagedAddLn", { bg = "#005523", fg = "#77787c" })
hi(0, "GitSignsStagedAddNr", { fg = "#597b60" })
hi(0, "GitSignsStagedChange", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangeLn", { bg = "#4f5258", fg = "#77787c" })
hi(0, "GitSignsStagedChangeNr", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangedelete", { fg = "#467c7b" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#4f5258", fg = "#77787c" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#467c7b" })
hi(0, "GitSignsStagedDelete", { fg = "#7f605c" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#7f605c" })
hi(0, "GitSignsStagedTopdelete", { fg = "#7f605c" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#7f605c" })
hi(0, "MiniStatuslineDevinfo", { link = "StatusLine" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { link = "StatusLineNC" })
hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
hi(0, "MiniStatuslineModeCommand", { link = "DiffText" })
hi(0, "MiniStatuslineModeInsert", { link = "DiffChange" })
hi(0, "MiniStatuslineModeNormal", { link = "RedrawDebugNormal" })
hi(0, "MiniStatuslineModeOther", { link = "IncSearch" })
hi(0, "MiniStatuslineModeReplace", { link = "DiffDelete" })
hi(0, "MiniStatuslineModeVisual", { link = "DiffAdd" })
hi(0, "MiniNotifyNormal", { link = "NvimDarkGrey4" })
hi(0, "MiniNotifyBorder", { link = "NvimDarkGrey4" })
hi(0, "MiniPickNormal", { link = "NvimDarkGrey4" })
hi(0, "MiniPickBorder", { link = "NvimDarkGrey4" })
hi(0, "LspReferenceRead", { bg = "#45475a" })
hi(0, "LspReferenceText", { bg = "#45475a" })
hi(0, "LspReferenceWrite", { bg = "#45475a" })
hi(0, "LspSignatureActiveParameter", { fg = "#d4aa55" })
